// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns \"Hello, World!\" to confirm the service is running.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Hello, World!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/player/add": {
            "post": {
                "description": "Adds a new player to the database. When KSFetchAvailable is enabled, profile data is fetched from the KingShot API; otherwise only the provided fields are stored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "summary": "Add a player",
                "parameters": [
                    {
                        "description": "Player to add",
                        "name": "player",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PlayerReqBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created Player examples\" examples(",
                        "schema": {
                            "$ref": "#/definitions/model.PlayerAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Unable to add the player",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/player/del/{pid}": {
            "delete": {
                "description": "Removes a player from the database by player ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "summary": "Delete a player",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "pid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Player deleted",
                        "schema": {
                            "$ref": "#/definitions/model.DeletePlayerResponse"
                        }
                    },
                    "404": {
                        "description": "Player not found",
                        "schema": {
                            "$ref": "#/definitions/model.DeletePlayerResponse"
                        }
                    },
                    "500": {
                        "description": "Delete failed",
                        "schema": {
                            "$ref": "#/definitions/model.DeletePlayerErrorResponse"
                        }
                    }
                }
            }
        },
        "/player/update/": {
            "patch": {
                "description": "Updates a single Player with the playerID provided in cia teh param",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "summary": "Updates the Db with latest Player Data of that player with same PlayerID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Player ID",
                        "name": "pid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UpdatePlayerSSE"
                        }
                    }
                }
            }
        },
        "/redeem/db": {
            "post": {
                "description": "Loads all players from the database and redeems the configured gift code for each one, streaming per-player results as Server-Sent Events (event: redeem-res) followed by a summary (event: redeem-fin). Rate limited.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Redeem"
                ],
                "summary": "Redeem gift code for all players",
                "parameters": [
                    {
                        "type": "string",
                        "example": "KS0803",
                        "description": "Gift code",
                        "name": "code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "redeem-res and redeem-fin event\" example(event: redeem-res\\ndata: {\"fid\":\"123\",\"code\":\"KS0803\",\"result\":{\"errCode\":20000,\"msg\":\"Redeemed\"},\"success\":true,\"time\":\"2026-08-07T22:05:40+05:30\"}\\n\\n event: redeem-fin\\ndata: {\"redeemed\":10,\"manual\":2,\"playerDead\":1,\"codeExpired\":3})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/redeem/ws": {
            "get": {
                "description": "Upgrades the connection to a WebSocket and greets the client.",
                "tags": [
                    "Redeem"
                ],
                "summary": "WebSocket test",
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.DeletePlayerErrorResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "pid": {
                    "type": "string"
                }
            }
        },
        "model.DeletePlayerResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "pid": {
                    "type": "string"
                },
                "player_info": {
                    "$ref": "#/definitions/model.PlayerInfo"
                }
            }
        },
        "model.PlayerAPIResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "player": {
                    "$ref": "#/definitions/model.PlayerInfo"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "model.PlayerInfo": {
            "type": "object",
            "properties": {
                "alliance": {
                    "type": "string"
                },
                "dName": {
                    "type": "string"
                },
                "kid": {
                    "type": "integer"
                },
                "pfp": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                }
            }
        },
        "model.PlayerReqBody": {
            "type": "object",
            "required": [
                "pid"
            ],
            "properties": {
                "alliance": {
                    "type": "string"
                },
                "kid": {
                    "type": "integer"
                },
                "pid": {
                    "type": "string"
                }
            }
        },
        "model.UpdatePlayerSSE": {
            "type": "object",
            "properties": {
                "player": {
                    "$ref": "#/definitions/model.PlayerInfo"
                },
                "updated": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Kingshot Redeem API",
	Description:      "API for redeeming KingShot gift codes on behalf of registered players. OpenAPI spec served at /api/openapi.json for import into GitBook.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
